; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = ../900_m5Gen/src
default_envs = debug

[env]
platform = espressif32 @ 6.5.0   ; ESP32-S3(CoreS3)対応のため 4.1.0 から更新
board = m5stack-cores3
framework = arduino

lib_deps = 
	m5stack/M5Unified@^0.2.2
	earlephilhower/ESP8266Audio@^1.9.7
    WiFi
;    symlink://../../../10_common
;    symlink://../../../20_platform/10_M5Stack
;    symlink://../../90_common

board_build.partitions = default_16MB.csv
build_src_filter = +<*>
    +<../../../90_testGen/010_common/src/testGen.cpp>
        +<../../../90_testGen/024_luminance/src/luminance.cpp>
        +<../../../90_testGen/024_luminance/src/picture.cpp>

lib_extra_dirs = 
    ../../../10_common
    ../../../20_platform/10_M5Stack
    ../../../90_testGen/024_luminance

build_flags =
    -std=gnu++17                                ; C++のバージョンを指定する
    -I ../../../10_common/src
    -I ../../../10_common/lib                   ; nlohmann-json
    -I ../../../20_platform/10_M5Stack/src      ;
    -I ../../../80_test/90_testGen/010_common/src
    

build_unflags =  -std=gnu++11   ; 古い標準設定を無効化する（念のため）
monitor_speed = 115200
monitor_filters = 
    direct                   ; ANSIエスケープ（色付きログ）を有効化
    esp32_exception_decoder  ; クラッシュ時のアドレスを関数名に変換
    
[env:release]
build_type = release

[env:debug]
build_type = debug
build_flags = 
    ${env.build_flags}
    -D _DEBUG
    -D _LOG_LVL=0
